In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('car_sales_data.csv')

In [3]:
df.head()

,Date,Salesperson,Customer Name,Car Make,Car Model,Car Year,Sale Price,Commission Rate,Commission Earned
0,2022-08-01,Monica Moore MD,Mary Butler,Nissan,Altima,2018,15983,0.070495,1126.73
1,2023-03-15,Roberto Rose,Richard Pierce,Nissan,F-150,2016,38474,0.134439,5172.40
2,2023-04-29,Ashley Ramos,Sandra Moore,Ford,Civic,2016,33340,0.114536,3818.63
3,2022-09-04,Patrick Harris,Johnny Scott,Ford,Altima,2013,41937,0.092191,3866.20
4,2022-06-16,Eric Lopez,Vanessa Jones,Honda,Silverado,2022,20256,0.113490,2298.85

In [4]:
max(pd.to_datetime(df.Date))

Timestamp('2023-05-01 00:00:00')

In [5]:
min(pd.to_datetime(df.Date))

Timestamp('2022-05-01 00:00:00')

In [6]:
max(pd.to_datetime(df.Date)) - min(pd.to_datetime(df.Date))

Timedelta('365 days 00:00:00')

In [7]:
(pd.to_datetime(df.Date)).unique()

<DatetimeArray>
['2022-08-01 00:00:00', '2023-03-15 00:00:00', '2023-04-29 00:00:00',
 '2022-09-04 00:00:00', '2022-06-16 00:00:00', '2022-12-18 00:00:00',
 '2022-06-12 00:00:00', '2022-06-20 00:00:00', '2022-09-02 00:00:00',
 '2023-04-06 00:00:00',
 ...
 '2022-06-05 00:00:00', '2022-07-10 00:00:00', '2023-01-15 00:00:00',
 '2022-06-24 00:00:00', '2022-07-20 00:00:00', '2022-10-17 00:00:00',
 '2022-09-10 00:00:00', '2022-12-15 00:00:00', '2022-08-03 00:00:00',
 '2022-09-14 00:00:00']
Length: 366, dtype: datetime64[ns]

In [8]:
df.groupby('Date').count().reset_index()

,Date,Salesperson,Customer Name,Car Make,Car Model,Car Year,Sale Price,Commission Rate,Commission Earned
0,2022-05-01,6887,6887,6887,6887,6887,6887,6887,6887
1,2022-05-02,6811,6811,6811,6811,6811,6811,6811,6811
2,2022-05-03,6810,6810,6810,6810,6810,6810,6810,6810
3,2022-05-04,6953,6953,6953,6953,6953,6953,6953,6953
4,2022-05-05,6815,6815,6815,6815,6815,6815,6815,6815
...,...,...,...,...,...,...,...,...,...
361,2023-04-27,6901,6901,6901,6901,6901,6901,6901,6901
362,2023-04-28,6890,6890,6890,6890,6890,6890,6890,6890
363,2023-04-29,6589,6589,6589,6589,6589,6589,6589,6589
364,2023-04-30,6808,6808,6808,6808,6808,6808,6808,6808
365,2023-05-01,6839,6839,6839,6839,6839,6839,6839,6839

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500000 entries, 0 to 2499999
Data columns (total 9 columns):
 #   Column             Dtype
---  ------             -----
 0   Date               object
 1   Salesperson        object
 2   Customer Name      object
 3   Car Make           object
 4   Car Model          object
 5   Car Year           int64
 6   Sale Price         int64
 7   Commission Rate    float64
 8   Commission Earned  float64
dtypes: float64(2), int64(2), object(5)
memory usage: 171.7+ MB

In [10]:
# create 4 years of data
full_df = df.copy()
days = 245
for i in range(6):
    df['Date'] = pd.to_datetime(df['Date']) - pd.DateOffset(days=days)
    full_df = pd.concat([full_df, df], axis=0)

In [17]:
days = 300
df['Date'] = pd.to_datetime(df['Date']) + pd.DateOffset(days=days)
full_df = pd.concat([full_df, df], axis=0)

In [12]:
print(max(pd.to_datetime(full_df.Date)) - min(pd.to_datetime(full_df.Date)))
print(full_df.shape)

2080 days 00:00:00
(20000000, 9)

In [19]:
max(pd.to_datetime(full_df.Date))

Timestamp('2025-08-23 00:00:00')

In [20]:
min(pd.to_datetime(full_df.Date))

Timestamp('2018-04-22 00:00:00')

In [21]:
# crear archivos por cada año mes de la data en full_df
for i in range(2018, 2026):
    for j in range(1, 13):
        try:
            df = full_df[(pd.to_datetime(full_df.Date).dt.year == i) & (pd.to_datetime(full_df.Date).dt.month == j)]
            df.to_csv(f'data/car_sales_data_{i}_{j}.csv', index=False)
            print(f'data/car_sales_data_{i}_{j}.csv')
        except:
            print(f'No data for {i} - {j}')

data/car_sales_data_2018_1.csv
data/car_sales_data_2018_2.csv
data/car_sales_data_2018_3.csv
data/car_sales_data_2018_4.csv
data/car_sales_data_2018_5.csv
data/car_sales_data_2018_6.csv
data/car_sales_data_2018_7.csv
data/car_sales_data_2018_8.csv
data/car_sales_data_2018_9.csv
data/car_sales_data_2018_10.csv
data/car_sales_data_2018_11.csv
data/car_sales_data_2018_12.csv
data/car_sales_data_2019_1.csv
data/car_sales_data_2019_2.csv
data/car_sales_data_2019_3.csv
data/car_sales_data_2019_4.csv
data/car_sales_data_2019_5.csv
data/car_sales_data_2019_6.csv
data/car_sales_data_2019_7.csv
data/car_sales_data_2019_8.csv
data/car_sales_data_2019_9.csv
data/car_sales_data_2019_10.csv
data/car_sales_data_2019_11.csv
data/car_sales_data_2019_12.csv
data/car_sales_data_2020_1.csv
data/car_sales_data_2020_2.csv
data/car_sales_data_2020_3.csv
data/car_sales_data_2020_4.csv
data/car_sales_data_2020_5.csv
data/car_sales_data_2020_6.csv
data/car_sales_data_2020_7.csv
data/car_sales_data_2020_8.csv
data/car_sales_data_2020_9.csv
data/car_sales_data_2020_10.csv
data/car_sales_data_2020_11.csv
data/car_sales_data_2020_12.csv
data/car_sales_data_2021_1.csv
data/car_sales_data_2021_2.csv
data/car_sales_data_2021_3.csv
data/car_sales_data_2021_4.csv
data/car_sales_data_2021_5.csv
data/car_sales_data_2021_6.csv
data/car_sales_data_2021_7.csv
data/car_sales_data_2021_8.csv
data/car_sales_data_2021_9.csv
data/car_sales_data_2021_10.csv
data/car_sales_data_2021_11.csv
data/car_sales_data_2021_12.csv
data/car_sales_data_2022_1.csv
data/car_sales_data_2022_2.csv
data/car_sales_data_2022_3.csv
data/car_sales_data_2022_4.csv
data/car_sales_data_2022_5.csv
data/car_sales_data_2022_6.csv
data/car_sales_data_2022_7.csv
data/car_sales_data_2022_8.csv
data/car_sales_data_2022_9.csv
data/car_sales_data_2022_10.csv
data/car_sales_data_2022_11.csv
data/car_sales_data_2022_12.csv
data/car_sales_data_2023_1.csv
data/car_sales_data_2023_2.csv
data/car_sales_data_2023_3.csv
data/car_sales_data_2023_4.csv
data/car_sales_data_2023_5.csv
data/car_sales_data_2023_6.csv
data/car_sales_data_2023_7.csv
data/car_sales_data_2023_8.csv
data/car_sales_data_2023_9.csv
data/car_sales_data_2023_10.csv
data/car_sales_data_2023_11.csv
data/car_sales_data_2023_12.csv
data/car_sales_data_2024_1.csv
data/car_sales_data_2024_2.csv
data/car_sales_data_2024_3.csv
data/car_sales_data_2024_4.csv
data/car_sales_data_2024_5.csv
data/car_sales_data_2024_6.csv
data/car_sales_data_2024_7.csv
data/car_sales_data_2024_8.csv
data/car_sales_data_2024_9.csv
data/car_sales_data_2024_10.csv
data/car_sales_data_2024_11.csv
data/car_sales_data_2024_12.csv
data/car_sales_data_2025_1.csv
data/car_sales_data_2025_2.csv
data/car_sales_data_2025_3.csv
data/car_sales_data_2025_4.csv
data/car_sales_data_2025_5.csv
data/car_sales_data_2025_6.csv
data/car_sales_data_2025_7.csv
data/car_sales_data_2025_8.csv
data/car_sales_data_2025_9.csv
data/car_sales_data_2025_10.csv
data/car_sales_data_2025_11.csv
data/car_sales_data_2025_12.csv